# .rubocop.yml - Rails API TODO Application
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/routes.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

# Allow longer lines for API responses and test descriptions
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Allow longer methods for controller actions with multiple operations
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

# Allow longer blocks in tests
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

# Allow larger ABC size for complex controller actions
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'

# Disable documentation requirement (API-only app)
Style/Documentation:
  Enabled: false

# Allow Russian comments and strings
Style/AsciiComments:
  Enabled: false

# Rails specific adjustments
Rails/I18nLocaleTexts:
  Enabled: false # We use Russian error messages directly