# .solargraph.yml
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
reporters:
  - rubocop
  - typecheck
require: []
domains: []
reporters:
  - rubocop
  - typecheck
require_paths: []
max_files: 5000